server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: host-microservice
              uri: lb://host-microservice
              predicates:
                - Path=/api/v1/hosts/**
            - id: booking-microservice
              uri: lb://booking-microservice
              predicates:
                  - Path=/api/v1/bookings/**
            - id: rooms-microservice
              uri: lb://rooms-microservice
              predicates:
                  - Path=/api/v1/rooms/**



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.netflix.discovery: DEBUG